[colors.primary]
background = '#010101'
foreground = '#d8d8d8'

[colors.cursor]
text = '#0D0E0E'
cursor = '#d8d8d8'

[colors.normal]
black   = '#0D0E0E'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#d8d8d8'

[colors.bright]
black   = '#585858'
red     = '#ab4642'
green   = '#a1b56c'
yellow  = '#f7ca88'
blue    = '#7cafc2'
magenta = '#ba8baf'
cyan    = '#86c1b9'
white   = '#f8f8f8'
[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "BitstromWera Nerd Font"
