# use C-a, since it's on the home row and easier to hit than C-b
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

# use 256 color terminal
set -g default-terminal 'screen-256color'
set -ga terminal-overrides ',*256col*:Tc'

# Splits
unbind |
bind | split-window -h -c "#{pane_current_path}"
unbind -
bind - split-window -v -c "#{pane_current_path}"

# Status bar
set -g status-bg black
set -g status-fg white
set -g status-interval 30
set -g status-left '#[fg=white][#S]#[default] '
set -g status-right ''

# Color of current window
setw -g window-status-current-style bg=yellow,fg=black

# Set window notifications
# setw -g monitor-activity on
# set -g visual-activity on

# Vim Escape
set -sg escape-time 0

# Vim Binds for splits and panes
bind-key v split-window -h
bind-key s split-window -v
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind-key -r J resize-pane -D 5
bind-key -r K resize-pane -U 5
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5

# Using the mouse
setw -g mouse on

