brew install 'git'
brew install 'python3'
brew install 'go'
brew install 'node'
brew install 'nmap'
brew install 'youtube-dl'
brew install 'speedtest-cli'
brew install 'ffmpeg'
brew install 'imagemagick'
brew install 'exiftools'
brew install 'mas'
brew install 'tldr'
brew install 'tmux'
brew install 'newsboat'
brew install 'tree'
brew install 'watch'
brew install 'gotop'
brew install 'htop'
brew install 'neovim'
brew install 'ghc' 
brew install 'cabal-install'
brew install 'hugo'
brew install 'mpv'

brew install --cask 'discord'
brew install --cask 'java'
brew install --cask 'signal'
brew install --cask 'vlc'
brew install --cask 'font-fira-code'
brew install --cask 'mullvadvpn'
brew install --cask 'whatsapp'
brew install --cask 'transmission'
brew install --cask 'dropbox'
brew install --cask 'bitwarden'
brew install --cask 'firefox'
brew install --cask 'handbrake'
brew install --cask 'sublime-text'
brew install --cask 'spotify'
brew install --cask 'libreoffice'
brew install --cask 'alacritty'
brew fetch 'eloston-chromium'
brew install --cask 'eloston-chromium'
brew install --cask 'iina'
brew install --cask 'dozer'
brew install --cask 'slack'
brew install --cask 'visual-studio-code'
brew install --cask 'brave-browser'
brew install --cask 'iterm2'
brew install --cask 'microsoft-teams'
brew install --cask 'spectacle'
brew install --cask 'selfcontrol'
brew install --cask 'veracrypt'
brew install --cask 'anki'
brew install --cask 'ledger-live'
brew install --cask 'monero-wallet'
brew install --cask 'monitorcontrol'
brew install --cask 'flux'

mas install '585829637'
