brew install 'git'
brew install 'python3'
brew install 'go'
brew install 'node'
brew install 'nmap'
brew install 'youtube-dl' 
brew install 'speedtest-cli'
brew install 'ffmpeg'
brew install 'imagemagick'
brew install 'exiftools'
brew install 'mas'
brew install 'tldr'
brew install 'tmux'
brew install 'newsboat'
brew install 'tree'
brew install 'watch'
brew install 'gotop'
brew install 'htop'

brew cask install 'discord'
brew cask install 'java'
brew cask install 'signal'
brew cask install 'vlc'
brew cask install 'font-fira-code'
brew cask install 'mullvadvpn'
brew cask install 'whatsapp'
brew cask install 'transmission'
brew cask install 'dropbox'
brew cask install 'bitwarden'
brew cask install 'firefox'
brew cask install 'handbrake'
brew cask install 'sublime-text'
brew cask install 'spotify'
brew cask install 'libreoffice'
brew cask install 'alacritty'
brew cask fetch 'eloston-chromium'
brew cask install 'eloston-chromium'
brew cask install 'iina'
brew cask install 'dozer'
